### ISSUE TITLE
Make a Flatpak package and publish on Flathub

### ISSUE THREAD

**Issue by Newbytee** [awesomekling/ladybird#2]
Hi!

Have you considered making a [Flatpak](https://flatpak.org) package of Ladybird that then can be published on [Flathub](https://flathub.org) for easier installation on Linux systems? It would also give you some publicity.

**Comment by son-link** [comment]
It's a great idea, but Flathub only accepts a stable versions, I know because I maintain 2 packages (Warzone 2100 and Speed Dreams, 2 open source games) .

If Andreas likes the idea, I offer myself for such a task in the future, even in AppImage format, which is to download, give run permissions and that's it.

**Comment by Newbytee** [comment]
Has it been said that no releases will be tagged for this software?

**Comment by ADKaster** [comment]
This experiment isn't ready for that kind of stability :).

If anything it will be merged into the SerenityOS/serenity repo where potential users can build it from source like everything else in serenity.

There are no tagged releases for any Serenity-derived software.

**Comment by Newbytee** [comment]
I see. In that case, does it make more sense to close this request?

**Comment by GerardoGR** [comment]
I think there are some options to consider before closing this issue:
- I've seen some instances of `Dev` flathub apps, e.g [com.google.ChromeDev](https://flathub.org/apps/details/com.google.ChromeDev), I guess the same could be done to ladybird. 
- In the official FlatHub, there is the concept of "nightly" builds but seems to be treated on case-by-case basis ([ref](https://github.com/flathub/flathub/issues/2975#issuecomment-1087266934)).
- Although more involved, the SerenityOS project could host their own FlatHub repository with their packages that will allow them to deploy the flatpaks continuously without following the guidelines from the official FlatHub.

**Comment by awesomekling** [comment]
Closing per @ADKaster's comments.

**Comment by niutech** [comment]
I've made the [AppImage](https://anonfiles.com/N28dV5zfy2/Ladybird-latest-x86_64_AppImage) for Linux x64 based on [this appimage-builder recipe](https://privatebin.net/?ecf88b27e33e31bf#iyFa7u2LjxJvMr9SQhqSeNNSbXcfUcrSSZwwrzdmtzN). It hasn't been tested outside my PC. If anybody want to optimize it, go ahead.

**Comment by igorlogius** [comment]
Instead of realsing it on the default/stable flathub repo , there is also th beta-repo.

https://dl.flathub.org/beta-repo/

That might be a good alternative for interested developers to follow the project/releases.

**Comment by 89z** [comment]
https://github.com/SerenityOS/ladybird/issues/33

**Comment by 1player** [comment]
I second @igorlogius. The beta repo is made exactly for this, the application won't appear in the Flathub or in any distribution repository by default, but enthusiasts might be able to follow along, and they will have to add the beta repository manually anyway.

I would definitely prefer the Flatpak in that case, as I'm technical enough to run the beta version, yet I'm not actively following this project enough to compile and run it myself at the moment.

**Comment by z3ntu** [comment]
Also nothing is forcing this to go on flathub, instead a custom flatpak remote can be set up (with the packages built in CI and deployed there) and all interested people just add that repo to their flatpak install.
