### ISSUE TITLE
OSX build

### ISSUE THREAD

**Issue by tronicum** [awesomekling/ladybird#8]
to my surpise, i was able to compile an OSX version using homebrew gcc as compiler. trying to open an page crashes though.
<img width="795" alt="ladybird-osx" src="https://user-images.githubusercontent.com/534773/177384286-4565d998-f73e-4566-93d8-8ee069625817.png">

**Comment by tronicum** [comment]
local stuff works though its not entirely broken.
<img width="444" alt="ladybird-local" src="https://user-images.githubusercontent.com/534773/177385164-3b23e9f7-cf67-401f-971c-13dd092791d2.png">

**Comment by ucosty** [comment]
I think the problem is caused by the browser not finding the ca_certs.ini file in the place it expects, which is /etc/ca_certs.ini.

There is slightly odd behavior in LibCore's config file routines which make opening a non-existent config file behave like opening an empty file.

**Comment by ADKaster** [comment]
The TLS library and other corresponding classes used by libweb  haven't been designed to execute outside of serenity where we have some hard coded expectations about where data files and resources will live. 

There's some work to go in the serenity libs to make all this behavior work properly in Linux

**Comment by fathonix** [comment]
Weird, mine works though.

<img width="1680" alt="Screen Shot 2022-07-06 at 05 51 30" src="https://user-images.githubusercontent.com/85305733/177429958-b0edb7fa-28f8-46ac-9088-cca582ddd483.png">

**Comment by fathonix** [comment]
YouTube and Facebook load but WhatIsMyBrowser.com crashes.

<img width="730" alt="Screen Shot 2022-07-06 at 05 59 08" src="https://user-images.githubusercontent.com/85305733/177430628-25f7c343-dfb2-4623-b5ac-3512ba30284c.png">

**Comment by nonetrix** [comment]
Funny I am on Arch Linux and having the exact same issue where pages crash seems like a larger issue
